In [1]:
import pandas as pd
import yaml
import numpy as np

In [2]:
with open("../config.yaml", "r") as file:
    config = yaml.safe_load(file)

In [3]:
config

{'data': {'raw': {'file1': '../data/raw/df_final_demo.txt',
   'file2': '../data/raw/df_final_experiment_clients.txt',
   'file3': '../data/raw/df_final_web_data_pt_1.txt',
   'file4': '../data/raw/df_final_web_data_pt_2.txt',
   'file5': '../data/raw/final_web_data_merged.csv'},
  'clean': {'file1': '../data/clean/df_demo_cleaned.csv',
   'file2': '../data/clean/df_experiment_clients_cleaned.csv',
   'file3': '../data/clean/df_test_cids.csv',
   'file4': '../data/clean/df_control_cids.csv',
   'file5': '../data/clean/final_web_data_merged_confirmed.csv',
   'file6': '../data/clean/df_merged_unique_vids.csv'}}}

In [4]:
df_w = pd.read_csv(config['data']['clean']['file6'], quotechar='"')
df_test= pd.read_csv(config['data']['clean']['file3'], quotechar='"')
df_cont= pd.read_csv(config['data']['clean']['file4'], quotechar='"')

In [5]:
#find most freq client to get a sense of the data
# top_client = df_w.client_id.value_counts().index[0]
# df_w[(df_w.client_id==top_client) & (df_w.process_step == 'confirm')]
# finished_ids = df_w[df_w.process_step == 'confirm'].client_id

In [6]:
df_wtest = df_w[df_w.client_id.isin(df_test.client_id)]
df_wcontrol = df_w[df_w.client_id.isin(df_cont.client_id)]

In [7]:
def contains_step_error(lst, sub):
    """
    function takes as input a list and looks for a sublist inside
    input: list and sub list
    output boolean
    """
    n = len(sub)
    return any(lst[i:i+n] == sub for i in range(len(lst)-n+1))

In [8]:
patterns = {
    's_1': ['start', 'step_1', 'start'],
    '1_2': ['step_1', 'step_2', 'step_1'],
    '2_3': ['step_2', 'step_3', 'step_2'],
    '3_c': ['step_3', 'confirm', 'step_3']
}
results = {key: set() for key in patterns}

for client_id, group in df_w.groupby('client_id'):
    step_list = group['process_step'].tolist()
    for key, pattern in patterns.items():
        if contains_step_error(step_list, pattern):
            results[key].add(client_id)

total = df_w['client_id'].nunique()
error_rates = {key: len(ids) / total for key, ids in results.items()}
print(error_rates)

{'s_1': 0.11171721770804147, '1_2': 0.04471665732698235, '2_3': 0.045706080134491456, '3_c': 3.502381619501261e-05}

In [9]:
steps = ['start', 'step_1', 'step_2', 'step_3', 'confirm']

def get_completion_rates(df):
    total = df['client_id'].nunique()
    rates = {}
    for step in steps:
        clients_reached = df[df['process_step'] == step]['client_id'].nunique()
        rates[step] = clients_reached #/ total
    return rates

In [10]:
def get_error_rate(df):
    patterns = {
        's_1': ['start', 'step_1', 'start'],
        '1_2': ['step_1', 'step_2', 'step_1'],
        '2_3': ['step_2', 'step_3', 'step_2'],
        '3_c': ['step_3', 'confirm', 'step_3']
    }
    results = {key: set() for key in patterns}
    err_ids = set()
    
    for client_id, group in df.groupby('client_id'):
        step_list = group['process_step'].tolist()
        for key, pattern in patterns.items():
            if contains_step_error(step_list, pattern):
                results[key].add(client_id)
                err_ids.add(client_id)
    
    # total = df['client_id'].nunique()
    # err_pc = len(err_ids)/total*100
    # error_rates = {key: len(ids) / total for key, ids in results.items()}
    error_rates = {key: len(ids) for key, ids in results.items()}
    error_rates['err_counts']=len(err_ids)   #err_pc
    results['err_counts']=err_ids
    return error_rates, results

In [11]:
finished_cont = get_completion_rates(df_wcontrol)
finished_test = get_completion_rates(df_wtest)

In [12]:
error_cont, res_cont = get_error_rate(df_wcontrol)
error_test, res_test = get_error_rate(df_wtest)
df_err_c = pd.DataFrame([error_cont])
df_err_t = pd.DataFrame([error_test])
df_err_c, df_err_t

(    s_1  1_2   2_3  3_c  err_counts
 0  1204  653  1370    0        3099,
     s_1   1_2   2_3  3_c  err_counts
 0  3273  1095  1137    1        5161)

In [13]:
from statsmodels.stats.proportion import proportions_ztest
ind=0
stats = {key: set() for key in res_test.keys()}
for col in res_test.keys():
    count_cont = list(finished_cont.values())[ind]
    count_test = list(finished_test.values())[ind]
    ind+=1
    stat, pval = proportions_ztest([len(res_cont[col]),len(res_test[col])],[count_cont,count_test])
    stats[col].add(pval)
    print(col, stat,pval)

s_1 -28.932371269210947 4.677014449337242e-184
1_2 -6.7317484479443035 1.6763628396239352e-11
2_3 9.782698123147329 1.3360062367967877e-22
3_c -0.9104769888125136 0.36257101188748275
err_counts -17.063297435526454 2.7838771573373833e-65

In [14]:
stats, finished_cont['confirm']/finished_cont['start'], finished_test['confirm']/finished_test['start']

({'s_1': {np.float64(4.677014449337242e-184)},
  '1_2': {np.float64(1.6763628396239352e-11)},
  '2_3': {np.float64(1.3360062367967877e-22)},
  '3_c': {np.float64(0.36257101188748275)},
  'err_counts': {np.float64(2.7838771573373833e-65)}},
 0.5556379175023982,
 0.6043406333700961)

In [15]:
len(res_cont['err_counts'])/finished_cont['confirm'], len(res_test['err_counts'])/finished_test['confirm']

(0.24319234089303932, 0.3363748940885094)

In [16]:
df_cd = pd.read_csv(config['data']['clean']['file1'], quotechar='"')

In [17]:
df_cd_c = df_cd[df_cd.client_id.isin(df_cont.client_id)]
df_cd_t = df_cd[df_cd.client_id.isin(df_test.client_id)]

In [18]:
df_wcontrol['date_time'] = pd.to_datetime(df_wcontrol['date_time'])
df_wtest['date_time'] = pd.to_datetime(df_wtest['date_time'])

In [19]:
# df_cd_c['group'] = 'control'
# df_cd_t['group'] = 'test'
# def add_error_cols(df_cd, df_w, results):
#     error_ids = results['err_counts']
#     pattern_keys = ['s_1', '1_2', '2_3', '3_c']
    
#     completion_times = df_w.groupby('client_id').agg(
#         completion_time=('date_time', lambda x: (x.max() - x.min()).total_seconds())
#     ).reset_index()
    
#     df_cd = df_cd.merge(completion_times, on='client_id', how='left')
#     df_cd['made_error'] = df_cd['client_id'].isin(error_ids)
#     df_cd['n_errors'] = df_cd['client_id'].apply(
#         lambda x: sum(x in results[key] for key in pattern_keys)
#     )
#     return df_cd

# df_cd_c = add_error_cols(df_cd_c, df_wcontrol, res_cont)
# df_cd_t = add_error_cols(df_cd_t, df_wtest, res_test)

# df_cd = pd.concat([df_cd_c, df_cd_t], ignore_index=True)

In [20]:
df_cd_c['group'] = 'control'
df_cd_t['group'] = 'test'

def get_completion_time(group):
    starts = group[group['process_step'] == 'start']['date_time']
    confirms = group[group['process_step'] == 'confirm']['date_time']
    if starts.empty or confirms.empty:
        return None
    return (confirms.max() - starts.max()) #.total_seconds()

def add_error_cols(df_cd, df_w, results):
    error_ids = results['err_counts']
    pattern_keys = ['s_1', '1_2', '2_3', '3_c']
    
    completion_times = df_w.groupby('client_id').apply(get_completion_time).reset_index()
    completion_times.columns = ['client_id', 'completion_time']
    
    df_cd = df_cd.merge(completion_times, on='client_id', how='left')
    df_cd['made_error'] = df_cd['client_id'].isin(error_ids)
    df_cd['n_errors'] = df_cd['client_id'].apply(
        lambda x: sum(x in results[key] for key in pattern_keys)
    )
    return df_cd

df_cd_c = add_error_cols(df_cd_c, df_wcontrol, res_cont)
df_cd_t = add_error_cols(df_cd_t, df_wtest, res_test)
df_cd = pd.concat([df_cd_c, df_cd_t], ignore_index=True)

In [32]:
df_cd = df_cd[df_cd['client_id'].isin(df_w['client_id'])]

In [33]:
df_cd

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,group,completion_time,made_error,n_errors,completion_hrs_mins,completed
0,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0,control,0 days 00:03:51,False,0,00:03:51,True
1,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0,control,NaT,False,0,NaT,False
2,3727881,5.0,71.0,30.5,U,2.0,23915.60,0.0,3.0,control,0 days 00:06:30,True,1,00:06:30,True
3,272934,5.0,66.0,58.5,U,2.0,27021.42,2.0,5.0,control,0 days 00:03:56,False,0,00:03:56,True
4,285619,30.0,369.0,67.5,M,2.0,299388.72,3.0,6.0,control,0 days 00:04:40,True,1,00:04:40,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50493,6751438,8.0,98.0,49.5,U,2.0,416988.75,6.0,9.0,test,0 days 00:03:20,False,0,00:03:20,True
50495,501496,23.0,281.0,35.0,F,2.0,32529.34,0.0,3.0,test,0 days 00:01:42,False,0,00:01:42,True
50496,1780858,21.0,262.0,68.5,M,3.0,372100.59,6.0,9.0,test,NaT,False,0,NaT,False
50498,8739285,19.0,229.0,69.5,F,2.0,44994.24,1.0,4.0,test,0 days 00:11:32,False,0,00:11:32,True
50499,7468138,18.0,222.0,61.0,F,3.0,209278.15,0.0,3.0,test,NaT,False,0,NaT,False

In [26]:
df_cd['completion_hrs_mins'] = (pd.Timestamp('1900-01-01') + df_cd['completion_time']).dt.time

In [27]:
df_cd['completed'] = df_cd['completion_time'].notna()

In [29]:
df_cd.completion_time.mean()
df_cd

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,group,completion_time,made_error,n_errors,completion_hrs_mins,completed
0,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0,control,0 days 00:03:51,False,0,00:03:51,True
1,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0,control,NaT,False,0,NaT,False
2,3727881,5.0,71.0,30.5,U,2.0,23915.60,0.0,3.0,control,0 days 00:06:30,True,1,00:06:30,True
3,272934,5.0,66.0,58.5,U,2.0,27021.42,2.0,5.0,control,0 days 00:03:56,False,0,00:03:56,True
4,285619,30.0,369.0,67.5,M,2.0,299388.72,3.0,6.0,control,0 days 00:04:40,True,1,00:04:40,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50495,501496,23.0,281.0,35.0,F,2.0,32529.34,0.0,3.0,test,0 days 00:01:42,False,0,00:01:42,True
50496,1780858,21.0,262.0,68.5,M,3.0,372100.59,6.0,9.0,test,NaT,False,0,NaT,False
50497,5826160,20.0,249.0,56.5,F,2.0,44837.16,2.0,5.0,test,NaT,False,0,NaT,False
50498,8739285,19.0,229.0,69.5,F,2.0,44994.24,1.0,4.0,test,0 days 00:11:32,False,0,00:11:32,True
50499,7468138,18.0,222.0,61.0,F,3.0,209278.15,0.0,3.0,test,NaT,False,0,NaT,False

In [30]:
df_cd.sort_values(by='completion_time', ascending=False)

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,group,completion_time,made_error,n_errors,completion_hrs_mins,completed
49443,6229511,14.0,176.0,65.5,F,2.0,33029.47,3.0,6.0,test,0 days 01:15:48,False,0,01:15:48,True
17451,9664057,29.0,349.0,51.0,F,2.0,64446.65,0.0,3.0,control,0 days 01:11:33,False,0,01:11:33,True
36141,847220,6.0,73.0,26.5,U,2.0,30070.09,2.0,5.0,test,0 days 01:10:04,False,0,01:10:04,True
10714,4533579,10.0,122.0,57.0,F,3.0,43772.69,1.0,4.0,control,0 days 00:58:46,False,0,00:58:46,True
45974,7977396,5.0,70.0,61.0,U,2.0,59640.97,1.0,4.0,test,0 days 00:58:40,False,0,00:58:40,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50489,2905735,15.0,190.0,46.0,M,2.0,208005.56,6.0,9.0,test,NaT,False,0,NaT,False
50494,6007167,25.0,301.0,49.5,M,2.0,64521.22,2.0,5.0,test,NaT,False,0,NaT,False
50496,1780858,21.0,262.0,68.5,M,3.0,372100.59,6.0,9.0,test,NaT,False,0,NaT,False
50497,5826160,20.0,249.0,56.5,F,2.0,44837.16,2.0,5.0,test,NaT,False,0,NaT,False
50499,7468138,18.0,222.0,61.0,F,3.0,209278.15,0.0,3.0,test,NaT,False,0,NaT,False

In [ ]:
# pd.qcut(df_cd['completion_seconds'].dropna(), q=4, labels=['Q1', 'Q2', 'Q3', 'Q4'])
df_cd.completion_seconds.median(), df_cd.completion_seconds.mean()

In [34]:
df_cd.to_csv("../data/clean/df_alldata.csv", index=False, encoding= "utf-8", sep = ",")

In [ ]:
df_cd[df_cd.client_id==1702]